# Generated by Django 6.0.4 on 2026-05-05 10:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название типа')),
                ('slug', models.SlugField(max_length=90, unique=True, verbose_name='Код для фильтра')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип аккумулятора',
                'verbose_name_plural': 'Типы аккумуляторов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Артикул должен состоять из латинских заглавных букв, цифр и дефисов.', regex='^[A-Z0-9-]+$')], verbose_name='Артикул')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('brand', models.CharField(max_length=80, verbose_name='Бренд')),
                ('capacity_mah', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500000)], verbose_name='Емкость, мАч')),
                ('voltage_v', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Напряжение, В')),
                ('starting_current_a', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3000)], verbose_name='Пусковой ток, А')),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)], verbose_name='Вес, г')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена, руб.')),
                ('stock_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='Остаток на складе')),
                ('warranty_months', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Гарантия, мес.')),
                ('fast_charge', models.BooleanField(default=False, verbose_name='Поддержка быстрой зарядки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('battery_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batteries', to='catalog.batterytype', verbose_name='Тип аккумулятора')),
            ],
            options={
                'verbose_name': 'Аккумулятор',
                'verbose_name_plural': 'Аккумуляторы',
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(check=models.Q(('price__gt', 0)), name='battery_price_positive'), models.CheckConstraint(check=models.Q(('capacity_mah__gt', 0)), name='battery_capacity_positive'), models.CheckConstraint(check=models.Q(('voltage_v__gt', 0)), name='battery_voltage_positive'), models.CheckConstraint(check=models.Q(('stock_quantity__gte', 0)), name='battery_stock_non_negative'), models.CheckConstraint(check=models.Q(('weight_grams__isnull', True), ('weight_grams__gt', 0), _connector='OR'), name='battery_weight_null_or_positive'), models.CheckConstraint(check=models.Q(('starting_current_a__isnull', True), ('starting_current_a__gt', 0), _connector='OR'), name='battery_starting_current_null_or_positive'), models.CheckConstraint(check=models.Q(('warranty_months__gte', 0), ('warranty_months__lte', 120)), name='battery_warranty_valid_range')],
            },
        ),
    ]
